### ISSUE TITLE
Version info

### ISSUE THREAD

**Issue by celer** [garrettux/knife-vagrant#1]
Hi,  what versions of Chef and Vagrant are you using? Trying to use your gem results in all sorts of errors due to version incompatibilities with Vagrant (0.9.7) and Chef (0.10.8)

**Comment by garrettux** [comment]
When I wrote this, I was using Vagrant 0.8.10 and chef 0.10.4, it was right around the end of 2011 before Vagrant 0.9 came out.  It's worth noting that I'm not actively working on this project right now.  I was working at a company that was using Vagrant at the time, but I'm not there anymore, so the chance that I'll be able to make any updates are very slim.

**Comment by garrettux** [comment]
closing.
