### ISSUE TITLE
provisioning_path should not be set for :chef_client provisioner

### ISSUE THREAD

**Issue by cap10morgan** [garrettux/knife-vagrant#2]
My knife vagrant commands were failing because it was attempting to run "mkdir -p" with no arguments. This was because the provisioning_path setting was set to an empty string.

According to the docs (http://vagrantup.com/v1/docs/provisioners/chef_server.html), provisioning_path seems to be a Chef Solo only setting. When I deleted the provisioning_path line from the Vagrantfile, the VM came up and the provisioner ran as expected.

Should the chef.provisioning_path = "#{Chef::Config[:provisioning_path]}" line be removed from the plugin?

**Comment by garrettux** [comment]
Good catch.  I honestly don't remember why chef.provisioning_path = "#{Chef::Config[:provisioning_path]}" was in there in the first place.  I never saw the error because I had provisioning_path set in my knife.rb.  I went ahead and took it out and pushed then changes.  Thanks!
